language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t scene-classifier .
  - docker run -it -d -p 5000:5000 scene-classifier

before_script:
  - pip install -r test-requirements.txt
  - sleep 30

script:
  - flake8 . --max-line-length=127
  - pytest tests/test.py
